### ISSUE TITLE
OOM on 48G gpu

### ISSUE THREAD

**Issue by PeterYYZhang** [Yuanshi9815/OminiControl#77]
I'm currently trying to train it using the a6000 ada gpus, I set the strategy to FSDP but it still reports OOM
Do we have to use 80gb memory for training?

**Comment by Yuanshi9815** [comment]
Hi @PeterYYZhang,

Just FYI - you should be able to run the 512x512 config on 48GB GPUs by enabling `gradient_checkpointing: true ` in your config.

:D

**Comment by PeterYYZhang** [comment]
Thanks @Yuanshi9815! Now it works!!

**Comment by rishabh063** [comment]
hey i am getting oom on 48gb vram even when gradient checkpoint is true
